services:
  api:
    image: ghcr.io/manuel-gallina/python-fastapi-v01:0.1.0-dev.1
    ports:
      - "9101:8000"
    command:
      - fastapi
      - run
      - /project/src/main.py
    environment:
      DATABASE__MAIN_CONNECTION__HOST: postgres
    volumes:
      - ./src:/project/src
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: python_fastapi_v01
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "9102:8080"
volumes:
  postgres_data: