[project]
name = "python-fastapi-v-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.2",
]

[dependency-groups]
dev = [
    "dagger-io>=0.19.11",
    "pytest>=9.0.2",
    "ruff>=0.15.0",
    "yappi>=1.7.3",
]

[tool.ruff.format]
skip-magic-trailing-comma = true