openapi: 3.1.0
info:
  title: FastAPI Template V1
  description: Template project for FastAPI applications.
  version: 0.1.0-dev.0
  x-logo:
    url: ./logo/logo.png
    altText: Logo
paths:
  /api/server-info:
    get:
      summary: Get Server Info
      description: Endpoint to retrieve server information, including version, current
        datetime and subsystems info.
      operationId: get_server_info_api_server_info_get
      responses:
        '200':
          description: Server information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponseSchema_GetServerInfoResponseSchema_'
components:
  schemas:
    DatabaseInfoSchema:
      properties:
        status:
          $ref: '#/components/schemas/ServerStatus'
          description: The status of the database connection.
        version:
          anyOf:
          - type: string
          - type: 'null'
          title: Version
          description: The version of the database server, if available.
      type: object
      required:
      - status
      title: DatabaseInfoSchema
    GetServerInfoResponseSchema:
      properties:
        serverVersion:
          type: string
          title: Serverversion
          description: The version of the server application.
        currentDatetime:
          type: string
          title: Currentdatetime
          description: The current date and time on the server.
        subsystems:
          $ref: '#/components/schemas/SubsystemsInfoSchema'
          description: Information about the server subsystems.
      type: object
      required:
      - serverVersion
      - currentDatetime
      - subsystems
      title: GetServerInfoResponseSchema
    ObjectResponseSchema_GetServerInfoResponseSchema_:
      properties:
        data:
          $ref: '#/components/schemas/GetServerInfoResponseSchema'
      type: object
      required:
      - data
      title: ObjectResponseSchema[GetServerInfoResponseSchema]
    ServerStatus:
      type: string
      enum:
      - ok
      - offline
      title: ServerStatus
    SubsystemsInfoSchema:
      properties:
        mainDb:
          $ref: '#/components/schemas/DatabaseInfoSchema'
          description: Information about the main database.
      type: object
      required:
      - mainDb
      title: SubsystemsInfoSchema
